CREATE DATABASE BETSY;
USE BETSY; 
CREATE TABLE TEAMS (
	TEAM_ID INT, 
	TEAM_NAME VARCHAR(255),  
	CITY VARCHAR(255)
);
 INSERT INTO TEST_TEAMS (TEAM_ID, TEAM_NAME, CITY) 
	VALUES (0, 'Example', 'Philadelphia');
