USE BETSY;
DELETE FROM teams;
INSERT INTO teams (teamID, teamName, city) VALUES (0, 'Alavés', 'Vitoria-Gasteiz');
INSERT INTO teams (teamID, teamName, city) VALUES (1, 'Athletic Bilbao', 'Bilbao');
INSERT INTO teams (teamID, teamName, city) VALUES (2, 'Atlético Madrid', 'Madrid');
INSERT INTO teams (teamID, teamName, city) VALUES (3, 'Barcelona', 'Barcelona');
INSERT INTO teams (teamID, teamName, city) VALUES (4, 'Celta Vigo', 'Vigo');
INSERT INTO teams (teamID, teamName, city) VALUES (5, 'Deportivo La Coruña', 'A Coruña');
INSERT INTO teams (teamID, teamName, city) VALUES (6, 'Eibar', 'Eibar');
INSERT INTO teams (teamID, teamName, city) VALUES (7, 'Espanyol', 'Cornellà de Llobregat');
INSERT INTO teams (teamID, teamName, city) VALUES (8, 'Getafe', 'Getafe');
INSERT INTO teams (teamID, teamName, city) VALUES (9, 'Girona', 'Girona');
INSERT INTO teams (teamID, teamName, city) VALUES (10, 'Las Palmas', 'Las Palmas');
INSERT INTO teams (teamID, teamName, city) VALUES (11, 'Leganés', 'Leganés');
INSERT INTO teams (teamID, teamName, city) VALUES (12, 'Levante', 'Valencia');
INSERT INTO teams (teamID, teamName, city) VALUES (13, 'Málaga', 'Málaga');
INSERT INTO teams (teamID, teamName, city) VALUES (14, 'Real Betis', 'Seville');
INSERT INTO teams (teamID, teamName, city) VALUES (15, 'Real Madrid', 'Madrid');
INSERT INTO teams (teamID, teamName, city) VALUES (16, 'Real Sociedad', 'San Sebastián');
INSERT INTO teams (teamID, teamName, city) VALUES (17, 'Sevilla', 'Sevilla');
INSERT INTO teams (teamID, teamName, city) VALUES (18, 'Valencia', 'Valencia');
INSERT INTO teams (teamID, teamName, city) VALUES (19, 'Villarreal', 'Villarreal');
SELECT * FROM teams;